### ISSUE TITLE
add registration pop up

### ISSUE THREAD

**Issue by nanonano7** [eosdac/eosdactoolkit#11]

**Comment by lukestokes** [comment]
Are you familiar with how to integrate the Ricardian Contracts for this?

**Comment by nanonano7** [comment]
![image](https://user-images.githubusercontent.com/30548940/43049820-976de5ee-8dfe-11e8-9bfe-3ba8a625e8fd.png)

like this. the rc text shows up like this on every transaction.
im currently working on replacing the {{fields}} in the text to whats being sent

**Comment by nanonano7** [comment]
![image](https://user-images.githubusercontent.com/30548940/43050042-9dc1f332-8e02-11e8-8f20-a8e6f27b294c.png)

this is how its looking now for every transaction.

**Comment by lukestokes** [comment]
I think we just want to show the the intent. Example from eos-voter:

![image](https://user-images.githubusercontent.com/344748/43051564-80943dfe-8de1-11e8-9dee-ca7ce14330d1.png)

**Comment by lukestokes** [comment]
Yeah, that works for me. Here's the EOS token contract as show in eos-voter: https://github.com/EOS-Mainnet/governance/blob/master/eosio.token/eosio.token-transfer-rc.md

![image](https://user-images.githubusercontent.com/344748/43055206-ebab50be-8dfa-11e8-9456-ee9116ef4546.png)

I'll check with @dali1986 on the wording. Since we started with the eos.io code, we should probably use their same Ricardian Contract as well. Tagging @dallasjohnson in case he has some thoughts as well.
