### ISSUE TITLE
Member registration

### ISSUE THREAD

**Issue by nanonano7** [eosdac/eosdactoolkit#4]
1.Present constitution to the user
2.Let the user agree to the constitution
3. Display ricardian contract section for memberreg action https://github.com/eosdac/eosdactoken/blob/ricardian-contract-ABI-additions/tokenmember_rc.md#action-memberreg
4.Hash constitution in markdown format
5.Send action
Where should the memberreg section be displayed?
I thought maybe in the intro right before getting to the actual main interface.

**Comment by lukestokes** [comment]
> I thought maybe in the intro right before getting to the actual main interface.

That works for me. Not sure why someone would want to use the eosDAC toolkit for anything unless they are registered members of the DAC.

**Comment by nanonano7** [comment]
I dont know how complete the constitution is but i converted it to markdown using some online tool
https://gist.github.com/nanonano7/8ae8d59dee0fff9a569a454839a3f60e

**Comment by lukestokes** [comment]
As far as I know, the current version is the final version we're going to live with as a DAC and future versions will involve changes that have to be agreed to.

Can you document the exact steps you took to get this? It seems like it needs a little manual clean up as well, but I'm thinking if we have all the steps and details, that could work so that anyone could follow the same process (convert the doc with the same tool, make the same manual formatting changes, etc), and then hash the document and get the same result.

Maybe if the manual clean-up changes are recorded as a diff, that would make it easier to verify.

**Comment by nanonano7** [comment]
what hashing algo should be used to hash the constitution?

**Comment by lukestokes** [comment]
@nanonano7 are you up to speed on how this is will be done in the contract?

![image](https://user-images.githubusercontent.com/344748/43049026-cfb8fef4-8db6-11e8-82d1-25bf3456e53e.png)

@dallasjohnson have these changes recommended by OCI been done yet?

**Comment by nanonano7** [comment]
should i load the constitiution over an ipfs gateway?

**Comment by kasperfish** [comment]
@nanonano7 yes because we can't hardcode the constitution in the app since it's a dynamic document and we should minimize relying on central servers.
